import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-inmuebles',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './inmuebles.component.html',
  styleUrl: './inmuebles.component.css'
})
export class InmueblesComponent {
  inmuebles=[
    {
      "referencia":"1",
      "descripcion":'Esta casa reformada en La Moraleja, con un cautivador estilo moderno y una arquitectura impresionante, ofrece una experiencia de vida contemporánea y lujosa. Con un ascensor para mayor comodidad y una elegante zona de bodega, esta propiedad redefine la elegancia. Además, su espectacular zona de barbacoa complementa perfectamente los espacios interiores, creando un ambiente ideal para el entretenimiento y el disfrute al aire libre. Suma Moraleja ofrece espectacular vivienda unifamiliar independiente con REFORMA INTEGRAL A ESTRENAR, con las mejores calidades y diseño, localizada en una de las principales arterias de La Moraleja. Novecientos treinta metros cuadrados construidos sobre parcela de 2600 metros. Destaca su paisajismo, elegante y sofisticado y la calidad de los materiales empleados en su construcción. El chalet se distribuye en dos plantas más la planta sótano.En la planta principal se ubican las zonas comunes con un elegante y amplísimo salón de 72 m2, también cuenta con un segundo salón o cuarto de estar de 47,50 m2 y una cocina con isla central comunicada con el comedor de 11 m2, las dimensiones y la luz natural hacen protagonistas a estas estancias. También en esta planta encontramos un coqueto patio interior con sus techos acristalados, vestíbulo y despacho que hacen de este espacio uno de los más especiales de la casa. En la primera planta encontramos dormitorio principal y 3 dormitorios completos, todos ellas con baño en suite. El dormitorio principal es una master suite, con dos baños, dos vestidores y acceso a una gran terraza. En la planta sótano, dispone de salón o sala de juegos de 21 m2, un estupendo dormitorio de invitados con baño en suite, gimnasio, bodega y un aseo. También una zona de servicio con dormitorio, baño y cuarto de lavandería. El garaje tiene capacidad para 4 coches en su interior. Su jardín de cuarto de hectárea es un verdadero paraíso de incuestionable belleza, que da el marco ideal y donde se alberga la piscina privada. Dispondrá del máximo confort y eficiencia energética gracias su climatización a través de geotermia con suelos radiantes y refrescantes.' ,
      "img": "https://s1.eestatic.com/2023/07/08/madrid/sociedad/777432409_234570572_1706x960.jpg"
    },
    {
      "referencia":"2",
      "descripcion":'Magnífico Chalet pareado en venta en Colmenar Viejo, El Mirador de Madrid. Situado en una exclusiva urbanización cerrada, este inmueble ofrece un estilo de vida de lujo y comodidad. Con zonas comunes que incluyen piscina, zona verde y gimnasio, podrás disfrutar de momentos de relax y diversión en tu propio hogar. La casa cuenta con tres plantas, ofreciendo amplios espacios para toda la familia. En la planta baja, encontrarás un hall que te dará la bienvenida a un luminoso salón-comedor de 40m2, perfecto para reuniones y celebraciones. La cocina americana moderna te permitirá preparar deliciosas comidas mientras interactúas con tus invitados. Además, podrás disfrutar de una terraza y un amplio jardín, ideal para tomar el sol o disfrutar de una barbacoa. En la primera planta, encontrarás tres dormitorios amplios, todos con múltiples armarios empotrados para almacenamiento adicional. Dos baños completos, uno de ellos en suite, te brindarán comodidad y privacidad. Uno de los dormitorios también cuenta con una terraza de 7m2, donde podrás relajarte y disfrutar de las vistas. La tercera planta te sorprenderá con un amplio dormitorio y un baño completo. Además, tendrás dos grandes terrazas de 28m2 y 15m2, donde podrás disfrutar de las vistas panorámicas y crear tus propios espacios al aire libre. El inmueble cuenta con pre-instalación de aire acondicionado, suelo radiante y placas solares para agua sanitaria, brindándote un mayor confort y eficiencia energética. Ubicado en una zona en pleno crecimiento, este chalet se encuentra rodeado de naturaleza y cuenta con servicios cercanos como colegios, centros de salud y supermercados. Además, estarás a tan solo 5 minutos del Centro Comercial Ventanal de la Sierra, donde encontrarás una amplia oferta de tiendas, restaurantes y ocio. Colmenar Viejo es un municipio con un casco histórico encantador, donde podrás disfrutar de la monumental Iglesia de la Asunción y descubrir su historia relacionada con El Real de Manzanares y la familia de los Mendoza. Con un desarrollo constante desde el siglo XIX, este municipio ha experimentado un incremento de población, sector servicios y construcción, lo que ha llevado a un aumento en la arquitectura urbana y la construcción de nuevas viviendas y segundas residencias.',
      "img": "https://eas.es/wp-content/uploads/2014/12/662-06.jpg" 

    },
    {
      "referencia":"3",
      "descripcion":'Precioso Loft en Loeches totalmente reformado con muy buen gusto para entrar a vivir. Alcalá inmobiliaria pone a su disposición este maravilloso loft, En urbanización privada con portero físico (24 horas), en garita a la entrada. Dos dormitorios, baño, cocina americana y gran salón con salida a un patio solado de 25 metros donde tenemos dos armarios trasteros. mas plaza de garaje. En  urbanización privada con seguridad las 24 horas del día los 365 días del año. Con zonas deportivas, (pista de tenis y pádel), dos piscinas (adultos e infantil) y zonas verdes. Entrando en la vivienda encontramos puerta principal blindada con cerradura de seguridad, hall de entrada con gran ventana, dormitorio principal doble con armario empotrado y gran ventana y doble comunicación con el baño y el salón, cocina americana con muebles altos y bajos mas electrodomésticos básicos, que da al gran salón con gran ventanal al patio, dormitorio doble con gran armario empotrado y una cristalera por la que entra mucha luz y  baño con plato de ducha y dos lavabos. La carpintería exterior es de aluminio blanco corredera  y persianas eléctricas automáticas, conectadas a la alarma, la carpintería interior de madera, suelos tarima con calefacción radiante eléctrica, el agua caliente es por termo eléctrico y la vivienda dispone de  aparatos de aire acondicionado con bomba de calor, plaza de garaje a la puerta de la misma. Los techos están asilados térmica y acústicamente, y la pared del salón se ha forrado de madera. La vivienda dispone de sistema de domótica conectado al móvil por el cual podrás apagar y encender la alarma, las luces, la calefacción y el agua caliente y subir y bajar las persianas. Además la vivienda dispone de preinstalación de cine en casa. Todo en perfecto estado y listo para entrar a vivir. En la urbanización encontramos zonas comunes con piscina de adultos y niños, pista de pádel y tenis y zonas ajardinadas.',
      "img": "https://pics.nuroa.com/medium/loft_en_venta_en_poligono_industrial_sur_7700011695903036042.jpg"
    }
  ]
}
